1th module solution
js-tasks-ru/jsbasic-20220711_horlov pull request #2
Opened 2022-07-17 15:00 UTC by GorlovVyacheslav

не совсем корректно получилось с 4й задачей учитывая ее условие, вот альтернативное решение через регулярное выражение:
function checkSpam(str) {
   return /1xBet|XXX/i.test(str);
}

2022-07-17 15:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-17 17:36 UTC, SinimaWath requested changes

2022-07-17 17:36 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    } return false;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return !!name && name.length >= 4 && ....`

Это как раз тот случай

2022-07-17 17:36 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    } return false;
Так же indexOf стараются не использовать, есть более понятный иногда метод: `includes` - который позволяет проверить, есть ли симвло в строке

2022-07-17 17:36 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
тут условие str && str.length лишнее. Его можно унести в if выше:
```
if (!str || str.length < 1) {
  return str;
}

return str.charAt(0).toUpperCase() + str.slice(1);
```

2022-07-17 17:36 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
`strToLower.includes('1xbet') || strToLower.includes('xxx')` - уже возвращает в качестве результате boolean. Поэтому нет необходимости в if: `return strToLower.includes('1xbet') || strToLower.includes('xxx')`

2022-07-18 08:11 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-18 13:02 UTC, SinimaWath approved these changes

2022-07-18 13:03 UTC, merged